### ISSUE TITLE
Failed to load plugin 'lingui' declared in '.eslintrc.json'

### ISSUE THREAD

**Issue by ealvarezk** [lingui/eslint-plugin#80]
I installed eslint-plugin-lingui dependency and the added to .eslintrc.json like this:
```
"extends": [
    "eslint:recommended",
    "next/core-web-vitals",
    "plugin:import/recommended",
    "plugin:import/typescript",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:@typescript-eslint/strict",
    "plugin:storybook/recommended",
    "plugin:@tanstack/eslint-plugin-query/recommended",
    "prettier",
    "plugin:lingui/recommended"
  ],
```
Then when I execute `next lint` I've got this error:

> **Failed to load plugin 'lingui' declared in '.eslintrc.json': Class extends value undefined is not a constructor or null**

**Comment by timofei-iatsenko** [comment]
What version of eslint?

**Comment by ealvarezk** [comment]
"8.41.0"

**Comment by ealvarezk** [comment]
Discard the issue, I fixed updating eslint to latest in 8

**Comment by timofei-iatsenko** [comment]
That's interesting issue. It happened because package manager installed a newer version of `@typescript-eslint/utils` which was not compatible with eslint version. 

I re-check the dependencies constraints for the plugin, it seems they are set correctly 

`"@typescript-eslint/utils": "^8.0.0"`

But (in my case yarn) installing `8.13.0` disregarding the fact that it's not compatible with eslint `8.37.0 - 8.41.0`. 

It seems it's happened because version of eslint is defined as direct constraint (`"8.37.0"`) in the app `package.json`. Changing this to the caret constraint will fix the issue, because package manager would be able to bump a workspace version of eslint satisfying peer dependencies.
